# Databricks notebook source
# MAGIC %md
# MAGIC ### Example Exploratory Notebook
# MAGIC
# MAGIC Use this notebook to explore the data generated by the pipeline in your preferred programming language.
# MAGIC
# MAGIC **Note**: This notebook is not executed as part of the pipeline.

# COMMAND ----------

import sys

sys.path.append("/Workspace/Users/hubert.dudek@brickschool.io/medium/news/202550/08 ForEachBatch sink for Lakeflow Spark Declarative Pipelines")

# COMMAND ----------

# !!! Before performing any data analysis, make sure to run the pipeline to materialize the sample datasets. The tables referenced in this notebook depend on that step.

display(spark.sql("SELECT * FROM hub.default.sample_aggregation_08_foreachbatch_sink_for_lakeflow_spark_declarative_pipelines"))
